[build]
  command = "npm run build"
  publish = "dist" # change to "build" if using CRA

# Redirect all frontend routes to index.html (React Router)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Proxy API requests to backend
[[redirects]]
  from = "/api/*"
  to = "https://global-connect-05.onrender.com/api/:splat"
  status = 200
  force = true
